#!/bin/sh

# Set layouts
setxkbmap -layout us,ru,ua -option grp:ctrl_shift_toggle -variant altgr-intl

# Start on launch
set-dpi &
mpd &
dunst &
remaps &
unclutter &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
xwallpaper --zoom ${XDG_CONFIG_HOME:-$HOME/.config}/wall.jpg

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
